spring.application.name=school-microservices

# Cоздаст таблицы при запуске
spring.jpa.hibernate.ddl-auto=update

# Показывать SQL запросы
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Диалект PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect