spring.application.name=school-microservices

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Cоздаст таблицы при запуске
spring.jpa.hibernate.ddl-auto=update

# Показывать SQL запросы
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Диалект PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect